on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: display env vars
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ../private.key
          cat ../private.key
          sudo chmod 600 ../private.key
          ssh-keyscan -H kl3xy.dev >> ~/.ssh/known_hosts
          ssh -i $SSH_KEY_PATH -Y cicd@kl3xy.dev << 'EOF'
            cd deploy
            echo "$CICD_PASSWORD" | sudo -S sh deploy.sh
          EOF
        shell: bash
        env:
          SSH_KEY: ${{secrets.DEPLOY_SSH_KEY}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          CICD_PASSWORD: ${{ secrets.CICD_PASSWORD }}


