on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: display env vars
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ../private.key
          sudo chmod 600 ../private.key
          ssh -i $SSH_KEY root@85.214.6.105
          sh deploy.sh
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.DEPLOY_SSH_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key


