on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: display env vars
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ../private.key
          sudo chmod 600 ../private.key
          ssh -i $SSH_KEY root@85.214.6.105
          sh deploy.sh
        shell: bash
        env:
          ENVIRONMENT_STAGE: ${{ vars.TEST_VARIABLE }}
          TEST_VAR: "Hello from the ting!"
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}


